[package]
name = "obsagent"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
obsagent-common = { path = "../common", features = ["user"] }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
env_logger = { workspace = true }
hdrhistogram = { workspace = true }
httparse = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
ratatui = { workspace = true, default-features = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
    "time",
    "sync",
    "io-util",
] }

[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
# Declared so cargo invalidates our build script when the BPF crate changes. The actual BPF
# build happens in build.rs (cargo-in-cargo), because it needs nightly + `-Z build-std`.
obsagent-ebpf = { path = "../ebpf" }

[[bin]]
name = "obsagent"
path = "src/main.rs"
